import Image from 'next/image'
import Head from 'next/head'
import Script from 'next/script'
import classNames from 'classnames/bind'
import { CgArrowRight } from 'react-icons/cg'
import Button from '@components/Button'
import { truncateText } from '@components/Util/Util'
import styles from './ProductItem.module.scss'

const cx = classNames.bind(styles)

interface ProductItemProps {
  id: string
  title: string
  description: string
  price: any[]
  image: string
  options?: string
  url: string
}

const ProductItem = ({ id, title, description, price, image, options, url }: ProductItemProps) => {
  console.log('price', price)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.css" />
      </Head>
      <div className={styles.item} key={id}>
        {image ? (
          <div>
            <Image
              src={image}
              alt={title}
              className={styles.item__image}
              width={475}
              height={300}
              priority
            />
          </div>
        ) : (
          <div className={cx('item__image', 'item__image--default')}></div>
        )}
        <div className={styles.item__title}>
          <p>{truncateText(title, 60)}</p>
        </div>
        <p className={styles.item__description}>
          {description.length > 154 ? truncateText(description, 154) : description}
        </p>
        <div>
          <p>${price}</p>
        </div>
        <div className={styles.item__container__button}>
          <button
            className={cx('snipcart-add-item', 'item__button', 'item__button--accent')}
            type="button"
            // accent
            data-item-id={id}
            data-item-price={price}
            data-item-url={`/vendor/${url}`}
            data-item-description={description}
            data-item-image={image}
            data-item-name={title}
          >
            Add to cart <CgArrowRight className={styles.icon} />
          </button>
        </div>
        <Script async src="https://cdn.snipcart.com/themes/v3.2.1/default/snipcart.js" />
        <div hidden id="snipcart" data-api-key={process.env.NEXT_PUBLIC_SNIPCART_API_KEY}></div>
      </div>
    </>
  )
}

export default ProductItem
