import Link from 'next/link'
import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '@components/Header'
import styles from '@styles/Home.module.scss'
import Container from '@components/Container'
import useHasMounted from '@components/hooks/useHasMounted'

import markets from '@data/markets.json'

export const getStaticProps: GetStaticProps = async () => {
  const vendors = markets
  return {
    props: {
      vendors,
    },
  }
}
const Home: NextPage = ({ vendors }: any) => {
  // console.log('markets', markets)
  const hasMounted = useHasMounted()
  if (!hasMounted) {
    return null
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>ecommerce-fm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <Container>
          <h1>HTX Farmer&apos;s Market</h1>
          <h2>Available shops</h2>
          <ul className={styles.products}>
            {vendors.map((vendor: any) => {
              return (
                <Link key={vendor.id} href={`/vendor/${vendor.id}`}>
                  <li>
                    <img src={vendor.image} />
                    <h3>{vendor.title}</h3>
                    <p>{vendor.description}</p>
                  </li>
                </Link>
              )
            })}
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        &copy; HTX Farmer&apos;s Market {new Date().getFullYear()}
      </footer>
    </div>
  )
}

export default Home
