import Link from 'next/link'
import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '@components/Header'
import styles from '@styles/Home.module.scss'
import Container from '@components/Container'
import useHasMounted from '@components/hooks/useHasMounted'

import markets from '@data/markets.json'
import Button from '@components/Button'
import Footer from '@components/Footer'
import Carousel from '@components/Carousel'

export const getStaticProps: GetStaticProps = async () => {
  const vendors = markets
  return {
    props: {
      vendors,
    },
  }
}
const Home: NextPage = ({ vendors }: any) => {
  // console.log('markets', markets)
  const hasMounted = useHasMounted()
  if (!hasMounted) {
    return null
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>ecommerce-fm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Container className={styles.padding}>
        <Carousel featuredPosts={vendors} />
        <main className={styles.main}>
          <h2>Available shops</h2>
          <ul className={styles.products}>
            {vendors.map((vendor: any) => {
              return (
                <Link key={vendor.id} href={`/vendor/${vendor.id}`}>
                  <li>
                    <img src={vendor.image} />
                    <h3>{vendor.title}</h3>
                    <p>{vendor.description}</p>
                    <Button primary>Visit Vendor</Button>
                  </li>
                </Link>
              )
            })}
          </ul>
        </main>
      </Container>
      <Footer />
    </div>
  )
}

export default Home
